### ISSUE TITLE
Do git checkout

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-fetcher#1]
For git dependencies, cargo uses a `CARGO_HOME/git/db` for bare clones of the git repo, and then uses `CARGO_HOME/git/checkouts` for the actual check outs used as sources when compiling.

Currently `cargo-fetcher` only does the bare clone portion leaving the checkout to cargo, which (I believe) does check outs one at a time, so this is probably another opportunity to reduce the total fetch time.

**Comment by cg-cnu** [comment]
Hey! 👋  Not a rust expert but dabbling in it for a while. Would love to pick this up.

**Comment by Jake-Shadle** [comment]
Sure, go for it! Right now all of the git operations are just shelling out to git, which is fine for the checkout from the bare clone as well, to test that you are doing the correct thing you can just delete any test crate from the checkout location and redo `sync` followed by a normal `cargo fetch`, which should be instant and do nothing if everything is correct.

Oh right...you'll probably want a way to disable the use of GCS since I only ever ran this with a valid GCS secret against one of our private buckets.
