### ISSUE TITLE
Support custom registries

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-fetcher#118]
Currently custom registries are not supported at all, and only crates.io is mirrored/fetched. We use a custom registry already which already non-fatal errors during mirroring due to this, so would be good to fix.

**Comment by m0ssc0de** [comment]
Hi. I'm trying to support custom registries.

I figured out that the download URL of a crate comes from a static string.

```rust
                let url = format!(
                    "https://static.crates.io/crates/{}/{}-{}.crate",
                    krate.name, krate.name, krate.version
                );
```

Then I tried to get the download URL from `.cargo/config.toml` and registry's `config.json` with the help of the crate `cargo` like this(https://github.com/m0ssc0de/cargo-fetcher/blob/main/src/util.rs#L679). But there is an error.

> `thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /Users/moss/.cargo/git/checkouts/cargo-e6ff02177275a46f/d887462/src/cargo/util/config/mod.rs:1252:9`.

I haven't figured out who holds the lock.

So do you have some advice on getting the download URL dynamically?

Thank you!

**Comment by Jake-Shadle** [comment]
Each registry index has a config.json file in the root which has a `dl` field with the base url to download crate files from.

**Comment by m0ssc0de** [comment]
The origin process of the ”mirror cmd” is mirroring the crates.io first. Then mirroring all crates parallelly.

Could we change the order?

The first model. Before mirror every crates, mirror it’s registry with caches and locks. We can also get the ’dl’ when mirroring the registry. 

The second model. Mirror all registry that is needed. Then mirror all crates like before.

Which one do you prefer? Or another better model?

**Comment by Jake-Shadle** [comment]
The easiest would probably be to just support having some cargo-fetcher metadata in the root cargo.toml (or .cargo/config.toml) which pairs a registry url with the download url for the crates, as that info doesn't really change often, and means you don't have to wait on a request to start uploading/downloading crates.

**Comment by m0ssc0de** [comment]
Yeah. It's a great idea. Let's try it.

**Comment by m0ssc0de** [comment]
Hi, the pr(https://github.com/EmbarkStudios/cargo-fetcher/pull/131) about custom registries have been created.
The whole development process took some detours. Hope it's not too late.
