### ISSUE TITLE
reached the type-length limit while instantiating `tokio::runtime::Handle::enter::<...()}]>>)]>, ()}]>}]>, ()}]>], ()>`

### ISSUE THREAD

**Issue by post-rex** [EmbarkStudios/cargo-fetcher#135]
**Describe the bug**
```
   Compiling cargo-fetcher v0.9.0
error: reached the type-length limit while instantiating `tokio::runtime::Handle::enter::<...()}]>>)]>, ()}]>}]>, ()}]>], ()>`
  --> /home/amnesia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:72:5
   |
72 | /     pub fn enter<F, R>(&self, f: F) -> R
73 | |     where
74 | |         F: FnOnce() -> R,
75 | |     {
76 | |         context::enter(self.clone(), f)
77 | |     }
   | |_____^
   |
   = note: consider adding a `#![type_length_limit="2014460"]` attribute to your crate

error: aborting due to previous error

error: failed to compile `cargo-fetcher v0.9.0`, intermediate artifacts can be found at `/tmp/cargo-installoI3KJo`

Caused by:
  could not compile `cargo-fetcher`.
```
Not much to explain, the rust compiler did a great job at it.
This is the case on my Linux laptop and windows work machine.

**To Reproduce**
1. `cargo install cargo-fetcher`

**Expected behavior**
cargo-fetcher installs.

**Device:**
1.
- ThinkPad T495s
- Manjaro Linux
- Linux Kernel: 5.8.6.1-MANJARO
- Cargo: 1.46.0
- Rustc: 1.46.0 (04488afe3 2020-08-24)
- Rustup: 1.22.1 (b01adbbc3 2020-07-08)
2.
- Wierd old Computer at Work
- Windows 10
- Cargo: ?
- Rustc: ?
- Rustup: ?

**Additional context**
Sorry if this issue sucks, I'm just not very sure what to put else here.

**Comment by Jake-Shadle** [comment]
I had this as well after updating to 1.46, but I haven't had it since updating to 1.47 or higher, so I'm closing this for now, sorry I'm late in closing this!
