### ISSUE TITLE
Replace bulky auto-generated crates

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-fetcher#157]
Right now both s3 and azure pull in a ridiculous amount of code and dependencies (often outdated!) for what essentially amounts to some authentication and a few HTTP calls, should try to replace them with something simpler like what the [tame-gcs](https://github.com/EmbarkStudios/tame-gcs/) is made to be, a thin sans-io interface.

- [x] azure #166 
- [x] s3 #161

**Comment by m0ssc0de** [comment]
@Jake-Shadle Hi Jake, the result of CI looks ok. Could you review this pr, if you have time?

**Comment by Jake-Shadle** [comment]
Thanks for posting these PRs and resolving this issue @m0ssc0de!
