### ISSUE TITLE
Update to tokio 1.0 ecosystem

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-fetcher#163]
Now that tokio 1.0 is out, and hyper/reqwest have been updated, it would be good to move to them, especially now that it is easier due to #161 has been merged, and the only holdout is azure.

**Comment by m0ssc0de** [comment]
Hi @Jake-Shadle, I'm trying to implement an Azure blob API lib, https://github.com/m0ssc0de/bloblock. I reckon it will help the `cargo-fetcher` update to tokio 1.0. 
My project is in the very initial stage. So if you have time, I'm glad to hear your suggestions.

**Comment by Jake-Shadle** [comment]
I don't have time to look at the exact code at the moment, but one thing that would make it a lot easier to review a future change that uses the crate would be if the crate itself was tested with the [Storage Emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator). I would probably want to add storage emulator tests to cargo-fetcher as well, but knowing the library was tested with it would at least be a really good start IMO.

**Comment by m0ssc0de** [comment]
Yeah. Testing with the real Azure service is a little bit hard. I will try to find an appropriate solution for the Storage Emulator.
