### ISSUE TITLE
S3 support

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-fetcher#3]
S3 support would be nice to have in addition to GCS.

**Comment by psinghal20** [comment]
Hi @Jake-Shadle @arirawr, I would like to work on this issue. Could you give me some pointers on where to start? Thanks!

**Comment by sbcd90** [comment]
Hi @psinghal20 , I'm already working on this issue & will provide a PR soon.

**Comment by Jake-Shadle** [comment]
Resolved by #8
